version: 1
hysteresis_default: 0.02
events:
  coalesce_window_ms: 200

# Optional global priorities when simultaneous thresholds fire
priorities:
  categories: ["health", "lifeforce", "lifespan", "qi", "spiritual", "mana", "stamina", "other"]

archetypes:
  warrior:
    stamina:
      thresholds:
        - id: low_stamina
          order: 10
          enter_percent_lte: 0.15
          exit_percent_gte: 0.17
          effects:
            - type: disable_cost_type
              values: ["stamina"]
            - type: damage_multiplier
              categories: ["physical"]
              modifier: -0.30
            - type: move_speed_modifier
              modifier: -0.20
            - type: disable_tags
              values: ["parry", "block"]
        
        - id: no_stamina
          order: 20
          enter_value_eq: 0
          effects:
            - type: action_lockout
              values: ["physical"]
            - type: stagger_susceptibility
              level: heavy
            - type: taunt_effectiveness_modifier
              modifier: -0.50

  mage:
    mana:
      thresholds:
        - id: low_mana
          order: 10
          enter_percent_lte: 0.10
          exit_percent_gte: 0.12
          effects:
            - type: disable_tags
              values: ["shield_activation", "buff_activation"]
            - type: damage_multiplier
              categories: ["magical", "elemental"]
              modifier: -0.40
            - type: incoming_multiplier
              categories: ["magical", "elemental"]
              modifier: 0.25
            - type: cast_time_modifier
              modifier: 0.30
        
        - id: no_mana
          order: 20
          enter_value_eq: 0
          effects:
            - type: disable_cost_type
              values: ["mana"]
            - type: break_active_shields
              values: ["MagicShield", "ElementalShield", "SpiritualShield"]
            - type: set_flag
              name: vulnerable_mage
              value: true

  # Default archetype for testing
  default:
    mana:
      thresholds:
        - id: low_mana
          order: 10
          enter_percent_lte: 0.10
          exit_percent_gte: 0.12
          effects:
            - type: disable_tags
              values: ["shield_activation"]
    
    stamina:
      thresholds:
        - id: low_stamina
          order: 10
          enter_percent_lte: 0.15
          exit_percent_gte: 0.17
          effects:
            - type: disable_cost_type
              values: ["stamina"]