version: 1

# Global defaults can be overridden per class/archetype/actor
defaults:
  evaluation_order:
    - shields
    - distribution
    - protections
    - update_values
    - exhaustion
    - events

archetypes:
  mage:
    mana:
      thresholds:
        - id: low_mana
          when_percent_lte: 0.10
          effects:
            - disable_tags: ["shield_activation", "buff_activation"]
            - damage_multiplier:
                categories: ["magical", "elemental", "spiritual"]
                modifier: -0.40
            - incoming_multiplier:
                categories: ["magical", "elemental"]
                modifier: 0.25
            - cast_time_modifier: 0.30
        - id: no_mana
          when_value_eq: 0
          effects:
            - disable_cost_type: ["mana"]
            - break_active_shields: ["MagicShield", "ElementalShield", "SpiritualShield"]
            - set_flag: { name: "vulnerable_mage", value: true }
  warrior:
    stamina:
      thresholds:
        - id: low_stamina
          when_percent_lte: 0.15
          effects:
            - disable_cost_type: ["stamina"]
            - damage_multiplier:
                categories: ["physical"]
                modifier: -0.30
            - move_speed_modifier: -0.20
            - disable_mechanics: ["block", "parry"]
        - id: no_stamina
          when_value_eq: 0
          effects:
            - action_lockout: ["physical"]
            - stagger_susceptibility: heavy
            - taunt_effectiveness_modifier: -0.50

generic:
  health:
    thresholds:
      - id: critical_health
        when_percent_lte: 0.10
        effects:
          # Choose one policy per mode: enrage or cripple
          - mode_overrides:
              pve: { damage_multiplier: { categories: ["all"], modifier: 0.15 } }
              pvp: { damage_multiplier: { categories: ["all"], modifier: -0.10 } }

events:
  coalesce_window_ms: 200
  emit:
    - ResourceExhaustedEvent
    - ResourceRecoveredEvent

