# Action Speed Multiplier Modifier Configuration
modifier_definition:
  # Basic Info
  modifier_id: "action_speed_multiplier"
  modifier_name: "Action Speed Multiplier"
  modifier_name_vi: "Hệ Số Nhân Tốc Độ Hành Động"
  
  # Modifier Properties
  modifier_type: "multiplier"
  priority: 160
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Modifier Description
  description: "Multiplies action speed based on magnitude and scaling factors"
  description_vi: "Nhân tốc độ hành động dựa trên cường độ và hệ số nhân"
  
  # Modifier Properties
  properties:
    value: 1.25
    source: "life_gift_buff"
    scaling_factor: 0.05
    scaling_stat: "agility"
    visual_effect: "action_speed_multiplier_indicator"
    audio_effect: "action_speed_multiplier_sound"
    
  # Modifier Rules
  rules:
    - rule_id: "action_speed_multiplier_calculation"
      rule_name: "Action Speed Multiplier Calculation"
      rule_name_vi: "Tính Toán Hệ Số Nhân Tốc Độ Hành Động"
      rule_type: "multiplier_calculation"
      rule_description: "Calculate action speed multiplier based on value and scaling factors"
      rule_formula: "speed_multiplier = base_value * (1 + scaling_factor * stat_value)"
      
    - rule_id: "action_speed_multiplier_application"
      rule_name: "Action Speed Multiplier Application"
      rule_name_vi: "Áp Dụng Hệ Số Nhân Tốc Độ Hành Động"
      rule_type: "multiplier_application"
      rule_description: "Apply action speed multiplier to speed calculation"
      rule_formula: "final_speed = base_speed * speed_multiplier"
      
    - rule_id: "action_speed_multiplier_stack_processing"
      rule_name: "Action Speed Multiplier Stack Processing"
      rule_name_vi: "Xử Lý Chồng Hệ Số Nhân Tốc Độ Hành Động"
      rule_type: "stack_processing"
      rule_description: "Process action speed multiplier stacking effects"
      rule_formula: "total_multiplier = sum(individual_multipliers) * stack_multiplier"
      
  # Modifier Interactions
  interactions:
    - interaction_id: "action_speed_multiplier_with_healing"
      interaction_name: "Action Speed Multiplier with Healing"
      interaction_name_vi: "Hệ Số Nhân Tốc Độ Hành Động với Hồi Máu"
      interaction_type: "conflict"
      target_modifier: "healing_multiplier"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "action_speed_multiplier_with_resistance"
      interaction_name: "Action Speed Multiplier with Resistance"
      interaction_name_vi: "Hệ Số Nhân Tốc Độ Hành Động với Kháng Cự"
      interaction_type: "resistance"
      target_modifier: "resistance_modifier"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Modifier Immunity
  immunity:
    - immunity_id: "action_speed_multiplier_immunity"
      immunity_name: "Action Speed Multiplier Immunity"
      immunity_name_vi: "Miễn Nhiễm Hệ Số Nhân Tốc Độ Hành Động"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Modifier Visual Effects
  visual_effects:
    - effect_id: "action_speed_multiplier_indicator"
      effect_name: "Action Speed Multiplier Indicator"
      effect_name_vi: "Chỉ Báo Hệ Số Nhân Tốc Độ Hành Động"
      effect_type: "indicator_effect"
      indicator_type: "multiplier"
      indicator_color: "#4ecdc4"
      indicator_intensity: 0.7
      
  # Modifier Audio Effects
  audio_effects:
    - effect_id: "action_speed_multiplier_sound"
      effect_name: "Action Speed Multiplier Sound"
      effect_name_vi: "Âm Thanh Hệ Số Nhân Tốc Độ Hành Động"
      effect_type: "ambient_sound"
      sound_type: "action"
      volume: 0.6
      loop: true
