# Rustfmt configuration for Actor Core

# Basic formatting
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "Vertical"

# Functions
fn_args_layout = "Tall"
fn_single_line = false

# Structs and enums
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# Comments
comment_width = 80
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Other
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_params_layout = "Tall"
where_single_line = true
imports_indent = "Block"
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
reorder_derive = true
reorder_attributes = true
