# Ambient Sound Audio Effect Configuration
audio_effect_definition:
  # Basic Info
  effect_id: "ambient_sound"
  effect_name: "Ambient Sound"
  effect_name_vi: "Âm Thanh Môi Trường"
  
  # Effect Properties
  effect_type: "ambient"
  priority: 100
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Effect Description
  description: "Creates ambient sound effects for status audio representation"
  description_vi: "Tạo hiệu ứng âm thanh môi trường cho biểu diễn âm thanh của trạng thái"
  
  # Effect Properties
  properties:
    sound_type: "damage"
    sound_volume: 0.7
    sound_loop: true
    sound_fade: true
    sound_pitch: 1.0
    sound_pan: 0.0
    sound_priority: 100
    sound_category: "status_effect"
    visual_effect: "ambient_sound_indicator"
    audio_effect: "ambient_sound_sound"
    
  # Effect Rules
  rules:
    - rule_id: "ambient_sound_calculation"
      rule_name: "Ambient Sound Calculation"
      rule_name_vi: "Tính Toán Âm Thanh Môi Trường"
      rule_type: "sound_calculation"
      rule_description: "Calculate ambient sound properties based on status magnitude and duration"
      rule_formula: "sound_volume = base_volume * status_magnitude * duration_multiplier"
      
    - rule_id: "ambient_sound_application"
      rule_name: "Ambient Sound Application"
      rule_name_vi: "Áp Dụng Âm Thanh Môi Trường"
      rule_type: "sound_application"
      rule_description: "Apply ambient sound effects to status audio representation"
      rule_formula: "ambient_sound = sound_system * sound_volume * sound_loop"
      
    - rule_id: "ambient_sound_animation"
      rule_name: "Ambient Sound Animation"
      rule_name_vi: "Hoạt Hình Âm Thanh Môi Trường"
      rule_type: "sound_animation"
      rule_description: "Animate ambient sound effects over time"
      rule_formula: "sound_animation = ambient_sound * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "ambient_sound_volume_multiplier"
      modifier_name: "Ambient Sound Volume Multiplier"
      modifier_name_vi: "Hệ Số Nhân Âm Lượng Âm Thanh Môi Trường"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "ambient_sound_pitch_multiplier"
      modifier_name: "Ambient Sound Pitch Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cao Độ Âm Thanh Môi Trường"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "ambient_sound_with_healing"
      interaction_name: "Ambient Sound with Healing"
      interaction_name_vi: "Âm Thanh Môi Trường với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_audio_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "ambient_sound_with_resistance"
      interaction_name: "Ambient Sound with Resistance"
      interaction_name_vi: "Âm Thanh Môi Trường với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_audio_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "ambient_sound_immunity"
      immunity_name: "Ambient Sound Immunity"
      immunity_name_vi: "Miễn Nhiễm Âm Thanh Môi Trường"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "ambient_sound_indicator"
      effect_name: "Ambient Sound Indicator"
      effect_name_vi: "Chỉ Báo Âm Thanh Môi Trường"
      effect_type: "indicator_effect"
      indicator_type: "sound"
      indicator_color: "#4ecdc4"
      indicator_intensity: 0.7
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "ambient_sound_sound"
      effect_name: "Ambient Sound Sound"
      effect_name_vi: "Âm Thanh Âm Thanh Môi Trường"
      effect_type: "ambient_sound"
      sound_type: "ambient"
      volume: 0.7
      loop: true
