# Conflict Sound Audio Effect Configuration
audio_effect_definition:
  # Basic Info
  effect_id: "conflict_sound"
  effect_name: "Conflict Sound"
  effect_name_vi: "Âm Thanh Xung Đột"
  
  # Effect Properties
  effect_type: "conflict"
  priority: 180
  stackable: false
  max_stacks: 1
  stack_behavior: "replace_all"
  
  # Effect Description
  description: "Creates conflict sound effects for status audio representation"
  description_vi: "Tạo hiệu ứng âm thanh xung đột cho biểu diễn âm thanh của trạng thái"
  
  # Effect Properties
  properties:
    sound_type: "damage"
    sound_volume: 0.8
    sound_loop: false
    sound_fade: true
    sound_pitch: 1.0
    sound_pan: 0.0
    sound_priority: 180
    sound_category: "status_effect"
    visual_effect: "conflict_sound_indicator"
    audio_effect: "conflict_sound_sound"
    
  # Effect Rules
  rules:
    - rule_id: "conflict_sound_calculation"
      rule_name: "Conflict Sound Calculation"
      rule_name_vi: "Tính Toán Âm Thanh Xung Đột"
      rule_type: "sound_calculation"
      rule_description: "Calculate conflict sound properties based on status magnitude and conflict value"
      rule_formula: "sound_volume = base_volume * status_magnitude * conflict_value_multiplier"
      
    - rule_id: "conflict_sound_application"
      rule_name: "Conflict Sound Application"
      rule_name_vi: "Áp Dụng Âm Thanh Xung Đột"
      rule_type: "sound_application"
      rule_description: "Apply conflict sound effects to status audio representation"
      rule_formula: "conflict_sound = sound_system * sound_volume * conflict_value"
      
    - rule_id: "conflict_sound_animation"
      rule_name: "Conflict Sound Animation"
      rule_name_vi: "Hoạt Hình Âm Thanh Xung Đột"
      rule_type: "sound_animation"
      rule_description: "Animate conflict sound effects over time"
      rule_formula: "sound_animation = conflict_sound * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "conflict_sound_volume_multiplier"
      modifier_name: "Conflict Sound Volume Multiplier"
      modifier_name_vi: "Hệ Số Nhân Âm Lượng Âm Thanh Xung Đột"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "conflict_sound_conflict_multiplier"
      modifier_name: "Conflict Sound Conflict Multiplier"
      modifier_name_vi: "Hệ Số Nhân Xung Đột Âm Thanh Xung Đột"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "conflict_sound_with_healing"
      interaction_name: "Conflict Sound with Healing"
      interaction_name_vi: "Âm Thanh Xung Đột với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_audio_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "conflict_sound_with_resistance"
      interaction_name: "Conflict Sound with Resistance"
      interaction_name_vi: "Âm Thanh Xung Đột với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_audio_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "conflict_sound_immunity"
      immunity_name: "Conflict Sound Immunity"
      immunity_name_vi: "Miễn Nhiễm Âm Thanh Xung Đột"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "conflict_sound_indicator"
      effect_name: "Conflict Sound Indicator"
      effect_name_vi: "Chỉ Báo Âm Thanh Xung Đột"
      effect_type: "indicator_effect"
      indicator_type: "sound"
      indicator_color: "#ff6b6b"
      indicator_intensity: 1.0
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "conflict_sound_sound"
      effect_name: "Conflict Sound Sound"
      effect_name_vi: "Âm Thanh Âm Thanh Xung Đột"
      effect_type: "instant_sound"
      sound_type: "conflict"
      volume: 0.8
      loop: false
