# Fade Sound Audio Effect Configuration
audio_effect_definition:
  # Basic Info
  effect_id: "fade_sound"
  effect_name: "Fade Sound"
  effect_name_vi: "Âm Thanh Fade"
  
  # Effect Properties
  effect_type: "fade"
  priority: 130
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Effect Description
  description: "Creates fading sound effects for status audio representation"
  description_vi: "Tạo hiệu ứng âm thanh fade cho biểu diễn âm thanh của trạng thái"
  
  # Effect Properties
  properties:
    sound_type: "damage"
    sound_volume: 0.6
    sound_loop: true
    sound_fade: true
    sound_pitch: 1.0
    sound_pan: 0.0
    sound_priority: 130
    sound_category: "status_effect"
    visual_effect: "fade_sound_indicator"
    audio_effect: "fade_sound_sound"
    
  # Effect Rules
  rules:
    - rule_id: "fade_sound_calculation"
      rule_name: "Fade Sound Calculation"
      rule_name_vi: "Tính Toán Âm Thanh Fade"
      rule_type: "sound_calculation"
      rule_description: "Calculate fade sound properties based on status magnitude and duration"
      rule_formula: "sound_volume = base_volume * status_magnitude * duration_multiplier * fade_multiplier"
      
    - rule_id: "fade_sound_application"
      rule_name: "Fade Sound Application"
      rule_name_vi: "Áp Dụng Âm Thanh Fade"
      rule_type: "sound_application"
      rule_description: "Apply fade sound effects to status audio representation"
      rule_formula: "fade_sound = sound_system * sound_volume * sound_fade"
      
    - rule_id: "fade_sound_animation"
      rule_name: "Fade Sound Animation"
      rule_name_vi: "Hoạt Hình Âm Thanh Fade"
      rule_type: "sound_animation"
      rule_description: "Animate fade sound effects over time"
      rule_formula: "sound_animation = fade_sound * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "fade_sound_volume_multiplier"
      modifier_name: "Fade Sound Volume Multiplier"
      modifier_name_vi: "Hệ Số Nhân Âm Lượng Âm Thanh Fade"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "fade_sound_fade_multiplier"
      modifier_name: "Fade Sound Fade Multiplier"
      modifier_name_vi: "Hệ Số Nhân Fade Âm Thanh Fade"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "fade_sound_with_healing"
      interaction_name: "Fade Sound with Healing"
      interaction_name_vi: "Âm Thanh Fade với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_audio_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "fade_sound_with_resistance"
      interaction_name: "Fade Sound with Resistance"
      interaction_name_vi: "Âm Thanh Fade với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_audio_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "fade_sound_immunity"
      immunity_name: "Fade Sound Immunity"
      immunity_name_vi: "Miễn Nhiễm Âm Thanh Fade"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "fade_sound_indicator"
      effect_name: "Fade Sound Indicator"
      effect_name_vi: "Chỉ Báo Âm Thanh Fade"
      effect_type: "indicator_effect"
      indicator_type: "sound"
      indicator_color: "#4ecdc4"
      indicator_intensity: 0.7
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "fade_sound_sound"
      effect_name: "Fade Sound Sound"
      effect_name_vi: "Âm Thanh Âm Thanh Fade"
      effect_type: "ambient_sound"
      sound_type: "fade"
      volume: 0.6
      loop: true
