# Immunity Sound Audio Effect Configuration
audio_effect_definition:
  # Basic Info
  effect_id: "immunity_sound"
  effect_name: "Immunity Sound"
  effect_name_vi: "Âm Thanh Miễn Nhiễm"
  
  # Effect Properties
  effect_type: "immunity"
  priority: 200
  stackable: false
  max_stacks: 1
  stack_behavior: "replace_all"
  
  # Effect Description
  description: "Creates immunity sound effects for status audio representation"
  description_vi: "Tạo hiệu ứng âm thanh miễn nhiễm cho biểu diễn âm thanh của trạng thái"
  
  # Effect Properties
  properties:
    sound_type: "immunity"
    sound_volume: 0.9
    sound_loop: false
    sound_fade: false
    sound_pitch: 1.0
    sound_pan: 0.0
    sound_priority: 200
    sound_category: "status_effect"
    visual_effect: "immunity_sound_indicator"
    audio_effect: "immunity_sound_sound"
    
  # Effect Rules
  rules:
    - rule_id: "immunity_sound_calculation"
      rule_name: "Immunity Sound Calculation"
      rule_name_vi: "Tính Toán Âm Thanh Miễn Nhiễm"
      rule_type: "sound_calculation"
      rule_description: "Calculate immunity sound properties based on status magnitude and immunity type"
      rule_formula: "sound_volume = base_volume * status_magnitude * immunity_type_multiplier"
      
    - rule_id: "immunity_sound_application"
      rule_name: "Immunity Sound Application"
      rule_name_vi: "Áp Dụng Âm Thanh Miễn Nhiễm"
      rule_type: "sound_application"
      rule_description: "Apply immunity sound effects to status audio representation"
      rule_formula: "immunity_sound = sound_system * sound_volume * immunity_duration"
      
    - rule_id: "immunity_sound_animation"
      rule_name: "Immunity Sound Animation"
      rule_name_vi: "Hoạt Hình Âm Thanh Miễn Nhiễm"
      rule_type: "sound_animation"
      rule_description: "Animate immunity sound effects over time"
      rule_formula: "sound_animation = immunity_sound * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "immunity_sound_volume_multiplier"
      modifier_name: "Immunity Sound Volume Multiplier"
      modifier_name_vi: "Hệ Số Nhân Âm Lượng Âm Thanh Miễn Nhiễm"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "element_mastery"
      
    - modifier_id: "immunity_sound_duration_multiplier"
      modifier_name: "Immunity Sound Duration Multiplier"
      modifier_name_vi: "Hệ Số Nhân Thời Lượng Âm Thanh Miễn Nhiễm"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "constitution"
      
  # Effect Interactions
  interactions:
    - interaction_id: "immunity_sound_with_healing"
      interaction_name: "Immunity Sound with Healing"
      interaction_name_vi: "Âm Thanh Miễn Nhiễm với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_audio_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.0
      
    - interaction_id: "immunity_sound_with_resistance"
      interaction_name: "Immunity Sound with Resistance"
      interaction_name_vi: "Âm Thanh Miễn Nhiễm với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_audio_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.0
      
  # Effect Immunity
  immunity:
    - immunity_id: "immunity_sound_immunity"
      immunity_name: "Immunity Sound Immunity"
      immunity_name_vi: "Miễn Nhiễm Âm Thanh Miễn Nhiễm"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "immunity_sound_indicator"
      effect_name: "Immunity Sound Indicator"
      effect_name_vi: "Chỉ Báo Âm Thanh Miễn Nhiễm"
      effect_type: "indicator_effect"
      indicator_type: "sound"
      indicator_color: "#ffd700"
      indicator_intensity: 1.0
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "immunity_sound_sound"
      effect_name: "Immunity Sound Sound"
      effect_name_vi: "Âm Thanh Âm Thanh Miễn Nhiễm"
      effect_type: "instant_sound"
      sound_type: "immunity"
      volume: 0.9
      loop: false
