# Instant Sound Audio Effect Configuration
audio_effect_definition:
  # Basic Info
  effect_id: "instant_sound"
  effect_name: "Instant Sound"
  effect_name_vi: "Âm Thanh Tức Thời"
  
  # Effect Properties
  effect_type: "instant"
  priority: 180
  stackable: false
  max_stacks: 1
  stack_behavior: "replace_all"
  
  # Effect Description
  description: "Creates instant sound effects for status audio representation"
  description_vi: "Tạo hiệu ứng âm thanh tức thời cho biểu diễn âm thanh của trạng thái"
  
  # Effect Properties
  properties:
    sound_type: "damage"
    sound_volume: 0.8
    sound_loop: false
    sound_fade: true
    sound_pitch: 1.0
    sound_pan: 0.0
    sound_priority: 200
    sound_category: "status_effect"
    visual_effect: "instant_sound_indicator"
    audio_effect: "instant_sound_sound"
    
  # Effect Rules
  rules:
    - rule_id: "instant_sound_calculation"
      rule_name: "Instant Sound Calculation"
      rule_name_vi: "Tính Toán Âm Thanh Tức Thời"
      rule_type: "sound_calculation"
      rule_description: "Calculate instant sound properties based on status magnitude and duration"
      rule_formula: "sound_volume = base_volume * status_magnitude * duration_multiplier"
      
    - rule_id: "instant_sound_application"
      rule_name: "Instant Sound Application"
      rule_name_vi: "Áp Dụng Âm Thanh Tức Thời"
      rule_type: "sound_application"
      rule_description: "Apply instant sound effects to status audio representation"
      rule_formula: "instant_sound = sound_system * sound_volume * sound_loop"
      
    - rule_id: "instant_sound_animation"
      rule_name: "Instant Sound Animation"
      rule_name_vi: "Hoạt Hình Âm Thanh Tức Thời"
      rule_type: "sound_animation"
      rule_description: "Animate instant sound effects over time"
      rule_formula: "sound_animation = instant_sound * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "instant_sound_volume_multiplier"
      modifier_name: "Instant Sound Volume Multiplier"
      modifier_name_vi: "Hệ Số Nhân Âm Lượng Âm Thanh Tức Thời"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "instant_sound_pitch_multiplier"
      modifier_name: "Instant Sound Pitch Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cao Độ Âm Thanh Tức Thời"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "instant_sound_with_healing"
      interaction_name: "Instant Sound with Healing"
      interaction_name_vi: "Âm Thanh Tức Thời với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_audio_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.3
      
    - interaction_id: "instant_sound_with_resistance"
      interaction_name: "Instant Sound with Resistance"
      interaction_name_vi: "Âm Thanh Tức Thời với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_audio_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.5
      
  # Effect Immunity
  immunity:
    - immunity_id: "instant_sound_immunity"
      immunity_name: "Instant Sound Immunity"
      immunity_name_vi: "Miễn Nhiễm Âm Thanh Tức Thời"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "instant_sound_indicator"
      effect_name: "Instant Sound Indicator"
      effect_name_vi: "Chỉ Báo Âm Thanh Tức Thời"
      effect_type: "indicator_effect"
      indicator_type: "sound"
      indicator_color: "#ff6b35"
      indicator_intensity: 1.0
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "instant_sound_sound"
      effect_name: "Instant Sound Sound"
      effect_name_vi: "Âm Thanh Âm Thanh Tức Thời"
      effect_type: "instant_sound"
      sound_type: "instant"
      volume: 0.8
      loop: false
