# Pulse Sound Audio Effect Configuration
audio_effect_definition:
  # Basic Info
  effect_id: "pulse_sound"
  effect_name: "Pulse Sound"
  effect_name_vi: "Âm Thanh Pulse"
  
  # Effect Properties
  effect_type: "pulse"
  priority: 140
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Effect Description
  description: "Creates pulsing sound effects for status audio representation"
  description_vi: "Tạo hiệu ứng âm thanh pulse cho biểu diễn âm thanh của trạng thái"
  
  # Effect Properties
  properties:
    sound_type: "healing"
    sound_volume: 0.6
    sound_loop: true
    sound_fade: true
    sound_pitch: 1.0
    sound_pan: 0.0
    sound_priority: 140
    sound_category: "status_effect"
    visual_effect: "pulse_sound_indicator"
    audio_effect: "pulse_sound_sound"
    
  # Effect Rules
  rules:
    - rule_id: "pulse_sound_calculation"
      rule_name: "Pulse Sound Calculation"
      rule_name_vi: "Tính Toán Âm Thanh Pulse"
      rule_type: "sound_calculation"
      rule_description: "Calculate pulse sound properties based on status magnitude and duration"
      rule_formula: "sound_volume = base_volume * status_magnitude * duration_multiplier * pulse_multiplier"
      
    - rule_id: "pulse_sound_application"
      rule_name: "Pulse Sound Application"
      rule_name_vi: "Áp Dụng Âm Thanh Pulse"
      rule_type: "sound_application"
      rule_description: "Apply pulse sound effects to status audio representation"
      rule_formula: "pulse_sound = sound_system * sound_volume * sound_pulse"
      
    - rule_id: "pulse_sound_animation"
      rule_name: "Pulse Sound Animation"
      rule_name_vi: "Hoạt Hình Âm Thanh Pulse"
      rule_type: "sound_animation"
      rule_description: "Animate pulse sound effects over time"
      rule_formula: "sound_animation = pulse_sound * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "pulse_sound_volume_multiplier"
      modifier_name: "Pulse Sound Volume Multiplier"
      modifier_name_vi: "Hệ Số Nhân Âm Lượng Âm Thanh Pulse"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "pulse_sound_pulse_multiplier"
      modifier_name: "Pulse Sound Pulse Multiplier"
      modifier_name_vi: "Hệ Số Nhân Pulse Âm Thanh Pulse"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "pulse_sound_with_healing"
      interaction_name: "Pulse Sound with Healing"
      interaction_name_vi: "Âm Thanh Pulse với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_audio_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "pulse_sound_with_resistance"
      interaction_name: "Pulse Sound with Resistance"
      interaction_name_vi: "Âm Thanh Pulse với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_audio_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "pulse_sound_immunity"
      immunity_name: "Pulse Sound Immunity"
      immunity_name_vi: "Miễn Nhiễm Âm Thanh Pulse"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "pulse_sound_indicator"
      effect_name: "Pulse Sound Indicator"
      effect_name_vi: "Chỉ Báo Âm Thanh Pulse"
      effect_type: "indicator_effect"
      indicator_type: "sound"
      indicator_color: "#ffd700"
      indicator_intensity: 0.8
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "pulse_sound_sound"
      effect_name: "Pulse Sound Sound"
      effect_name_vi: "Âm Thanh Âm Thanh Pulse"
      effect_type: "ambient_sound"
      sound_type: "pulse"
      volume: 0.6
      loop: true
