# Synergy Sound Audio Effect Configuration
audio_effect_definition:
  # Basic Info
  effect_id: "synergy_sound"
  effect_name: "Synergy Sound"
  effect_name_vi: "Âm Thanh Hiệp Lực"
  
  # Effect Properties
  effect_type: "synergy"
  priority: 140
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Effect Description
  description: "Creates synergy sound effects for status audio representation"
  description_vi: "Tạo hiệu ứng âm thanh hiệp lực cho biểu diễn âm thanh của trạng thái"
  
  # Effect Properties
  properties:
    sound_type: "healing"
    sound_volume: 0.6
    sound_loop: true
    sound_fade: true
    sound_pitch: 1.0
    sound_pan: 0.0
    sound_priority: 140
    sound_category: "status_effect"
    visual_effect: "synergy_sound_indicator"
    audio_effect: "synergy_sound_sound"
    
  # Effect Rules
  rules:
    - rule_id: "synergy_sound_calculation"
      rule_name: "Synergy Sound Calculation"
      rule_name_vi: "Tính Toán Âm Thanh Hiệp Lực"
      rule_type: "sound_calculation"
      rule_description: "Calculate synergy sound properties based on status magnitude and synergy value"
      rule_formula: "sound_volume = base_volume * status_magnitude * synergy_value_multiplier"
      
    - rule_id: "synergy_sound_application"
      rule_name: "Synergy Sound Application"
      rule_name_vi: "Áp Dụng Âm Thanh Hiệp Lực"
      rule_type: "sound_application"
      rule_description: "Apply synergy sound effects to status audio representation"
      rule_formula: "synergy_sound = sound_system * sound_volume * synergy_value"
      
    - rule_id: "synergy_sound_animation"
      rule_name: "Synergy Sound Animation"
      rule_name_vi: "Hoạt Hình Âm Thanh Hiệp Lực"
      rule_type: "sound_animation"
      rule_description: "Animate synergy sound effects over time"
      rule_formula: "sound_animation = synergy_sound * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "synergy_sound_volume_multiplier"
      modifier_name: "Synergy Sound Volume Multiplier"
      modifier_name_vi: "Hệ Số Nhân Âm Lượng Âm Thanh Hiệp Lực"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "synergy_sound_synergy_multiplier"
      modifier_name: "Synergy Sound Synergy Multiplier"
      modifier_name_vi: "Hệ Số Nhân Hiệp Lực Âm Thanh Hiệp Lực"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "synergy_sound_with_healing"
      interaction_name: "Synergy Sound with Healing"
      interaction_name_vi: "Âm Thanh Hiệp Lực với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_audio_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "synergy_sound_with_resistance"
      interaction_name: "Synergy Sound with Resistance"
      interaction_name_vi: "Âm Thanh Hiệp Lực với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_audio_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "synergy_sound_immunity"
      immunity_name: "Synergy Sound Immunity"
      immunity_name_vi: "Miễn Nhiễm Âm Thanh Hiệp Lực"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "synergy_sound_indicator"
      effect_name: "Synergy Sound Indicator"
      effect_name_vi: "Chỉ Báo Âm Thanh Hiệp Lực"
      effect_type: "indicator_effect"
      indicator_type: "sound"
      indicator_color: "#ffd700"
      indicator_intensity: 0.8
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "synergy_sound_sound"
      effect_name: "Synergy Sound Sound"
      effect_name_vi: "Âm Thanh Âm Thanh Hiệp Lực"
      effect_type: "ambient_sound"
      sound_type: "synergy"
      volume: 0.6
      loop: true
