server:
  port: 8083
  host: "0.0.0.0"
  workers: 4

database:
  mongodb_uri: "mongodb://localhost:27017"
  mongodb_database: "chaos_cms"

auth:
  jwt_secret: "your_jwt_secret_here_change_in_production_use_strong_secret_key"
  jwt_expiry: 3600
  admin_username: "admin"
  admin_password: "admin123"

monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_enabled: true
