# Development Configuration for CMS Service
server:
  port: 8080
  host: "0.0.0.0"
  workers: 2

database:
  mongodb_uri: "mongodb://localhost:27017"
  mongodb_database: "chaos_cms_dev"

auth:
  jwt_secret: "dev_jwt_secret_change_in_production"
  jwt_expiry: 3600
  admin_username: "admin"
  admin_password: "admin123"

monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_enabled: true

logging:
  level: "debug"
  format: "pretty"
