server:
  host: "0.0.0.0"
  port: 8080

routing:
  service_discovery:
    static_services:
      user-management:
        host: "localhost"
        port: 8082
        health_check: "/health"
      chaos-backend:
        host: "localhost"
        port: 8081
        health_check: "/health"

  routes:
    # Authentication routes
    - path: "/auth/*"
      service: "user-management"
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      strip_prefix: false
      add_headers:
        X-Forwarded-By: "api-gateway"
      rate_limit:
        requests_per_minute: 100
        burst_size: 10

    # API routes
    - path: "/api/*"
      service: "chaos-backend"
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      strip_prefix: true
      add_headers:
        X-Forwarded-By: "api-gateway"
      rate_limit:
        requests_per_minute: 200
        burst_size: 20

    # API root route (maps /api/ to /)
    - path: "/api"
      service: "chaos-backend"
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      strip_prefix: true
      add_headers:
        X-Forwarded-By: "api-gateway"
      rate_limit:
        requests_per_minute: 200
        burst_size: 20


    # Health check routes (no rate limiting)
    - path: "/health"
      service: "user-management"
      methods: ["GET"]
      strip_prefix: true
      add_headers:
        X-Forwarded-By: "api-gateway"