# Aura Effect Visual Effect Configuration
visual_effect_definition:
  # Basic Info
  effect_id: "aura_effect"
  effect_name: "Aura Effect"
  effect_name_vi: "Hiệu Ứng Hào Quang"
  
  # Effect Properties
  effect_type: "aura"
  priority: 150
  stackable: true
  max_stacks: 3
  stack_behavior: "stack_additive"
  
  # Effect Description
  description: "Creates aura effects around actors for status visual representation"
  description_vi: "Tạo hiệu ứng hào quang xung quanh diễn viên cho biểu diễn trực quan của trạng thái"
  
  # Effect Properties
  properties:
    aura_type: "circular"
    aura_color: "#ffd700"
    aura_intensity: 0.8
    aura_radius: 2.0
    aura_pulse: true
    aura_rotation: false
    aura_fade: true
    aura_loop: true
    visual_effect: "aura_effect_indicator"
    audio_effect: "aura_effect_sound"
    
  # Effect Rules
  rules:
    - rule_id: "aura_effect_calculation"
      rule_name: "Aura Effect Calculation"
      rule_name_vi: "Tính Toán Hiệu Ứng Hào Quang"
      rule_type: "aura_calculation"
      rule_description: "Calculate aura effect properties based on status magnitude and duration"
      rule_formula: "aura_intensity = base_intensity * status_magnitude * duration_multiplier"
      
    - rule_id: "aura_effect_application"
      rule_name: "Aura Effect Application"
      rule_name_vi: "Áp Dụng Hiệu Ứng Hào Quang"
      rule_type: "aura_application"
      rule_description: "Apply aura effects to status visual representation"
      rule_formula: "aura_effect = aura_system * aura_intensity * aura_radius"
      
    - rule_id: "aura_effect_animation"
      rule_name: "Aura Effect Animation"
      rule_name_vi: "Hoạt Hình Hiệu Ứng Hào Quang"
      rule_type: "aura_animation"
      rule_description: "Animate aura effects over time"
      rule_formula: "aura_animation = aura_effect * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "aura_intensity_multiplier"
      modifier_name: "Aura Intensity Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cường Độ Hào Quang"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "aura_radius_multiplier"
      modifier_name: "Aura Radius Multiplier"
      modifier_name_vi: "Hệ Số Nhân Bán Kính Hào Quang"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "aura_effect_with_healing"
      interaction_name: "Aura Effect with Healing"
      interaction_name_vi: "Hiệu Ứng Hào Quang với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_visual_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "aura_effect_with_resistance"
      interaction_name: "Aura Effect with Resistance"
      interaction_name_vi: "Hiệu Ứng Hào Quang với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_visual_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "aura_effect_immunity"
      immunity_name: "Aura Effect Immunity"
      immunity_name_vi: "Miễn Nhiễm Hiệu Ứng Hào Quang"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "aura_effect_indicator"
      effect_name: "Aura Effect Indicator"
      effect_name_vi: "Chỉ Báo Hiệu Ứng Hào Quang"
      effect_type: "indicator_effect"
      indicator_type: "aura"
      indicator_color: "#ffd700"
      indicator_intensity: 0.8
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "aura_effect_sound"
      effect_name: "Aura Effect Sound"
      effect_name_vi: "Âm Thanh Hiệu Ứng Hào Quang"
      effect_type: "ambient_sound"
      sound_type: "aura"
      volume: 0.5
      loop: true
