# Conflict Effect Visual Effect Configuration
visual_effect_definition:
  # Basic Info
  effect_id: "conflict_effect"
  effect_name: "Conflict Effect"
  effect_name_vi: "Hiệu Ứng Xung Đột"
  
  # Effect Properties
  effect_type: "conflict"
  priority: 180
  stackable: false
  max_stacks: 1
  stack_behavior: "replace_all"
  
  # Effect Description
  description: "Creates conflict effects for status visual representation"
  description_vi: "Tạo hiệu ứng xung đột cho biểu diễn trực quan của trạng thái"
  
  # Effect Properties
  properties:
    conflict_type: "effectiveness_reduction"
    conflict_color: "#ff6b6b"
    conflict_intensity: 1.0
    conflict_value: 0.5
    conflict_size: 1.0
    conflict_rotation: false
    conflict_pulse: false
    conflict_fade: true
    conflict_loop: true
    visual_effect: "conflict_effect_indicator"
    audio_effect: "conflict_effect_sound"
    
  # Effect Rules
  rules:
    - rule_id: "conflict_effect_calculation"
      rule_name: "Conflict Effect Calculation"
      rule_name_vi: "Tính Toán Hiệu Ứng Xung Đột"
      rule_type: "conflict_calculation"
      rule_description: "Calculate conflict effect properties based on status magnitude and conflict value"
      rule_formula: "conflict_intensity = base_intensity * status_magnitude * conflict_value_multiplier"
      
    - rule_id: "conflict_effect_application"
      rule_name: "Conflict Effect Application"
      rule_name_vi: "Áp Dụng Hiệu Ứng Xung Đột"
      rule_type: "conflict_application"
      rule_description: "Apply conflict effects to status visual representation"
      rule_formula: "conflict_effect = conflict_system * conflict_intensity * conflict_value"
      
    - rule_id: "conflict_effect_animation"
      rule_name: "Conflict Effect Animation"
      rule_name_vi: "Hoạt Hình Hiệu Ứng Xung Đột"
      rule_type: "conflict_animation"
      rule_description: "Animate conflict effects over time"
      rule_formula: "conflict_animation = conflict_effect * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "conflict_intensity_multiplier"
      modifier_name: "Conflict Intensity Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cường Độ Xung Đột"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "conflict_value_multiplier"
      modifier_name: "Conflict Value Multiplier"
      modifier_name_vi: "Hệ Số Nhân Giá Trị Xung Đột"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "conflict_effect_with_healing"
      interaction_name: "Conflict Effect with Healing"
      interaction_name_vi: "Hiệu Ứng Xung Đột với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_visual_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "conflict_effect_with_resistance"
      interaction_name: "Conflict Effect with Resistance"
      interaction_name_vi: "Hiệu Ứng Xung Đột với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_visual_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "conflict_effect_immunity"
      immunity_name: "Conflict Effect Immunity"
      immunity_name_vi: "Miễn Nhiễm Hiệu Ứng Xung Đột"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "conflict_effect_indicator"
      effect_name: "Conflict Effect Indicator"
      effect_name_vi: "Chỉ Báo Hiệu Ứng Xung Đột"
      effect_type: "indicator_effect"
      indicator_type: "conflict"
      indicator_color: "#ff6b6b"
      indicator_intensity: 1.0
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "conflict_effect_sound"
      effect_name: "Conflict Effect Sound"
      effect_name_vi: "Âm Thanh Hiệu Ứng Xung Đột"
      effect_type: "instant_sound"
      sound_type: "conflict"
      volume: 0.8
      loop: false
