# Enhancement Effect Visual Effect Configuration
visual_effect_definition:
  # Basic Info
  effect_id: "enhancement_effect"
  effect_name: "Enhancement Effect"
  effect_name_vi: "Hiệu Ứng Tăng Cường"
  
  # Effect Properties
  effect_type: "enhancement"
  priority: 140
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Effect Description
  description: "Creates enhancement effects for status visual representation"
  description_vi: "Tạo hiệu ứng tăng cường cho biểu diễn trực quan của trạng thái"
  
  # Effect Properties
  properties:
    enhancement_type: "magnitude_increase"
    enhancement_color: "#ffd700"
    enhancement_intensity: 0.8
    enhancement_value: 0.25
    enhancement_size: 0.7
    enhancement_rotation: true
    enhancement_pulse: true
    enhancement_fade: true
    enhancement_loop: true
    visual_effect: "enhancement_effect_indicator"
    audio_effect: "enhancement_effect_sound"
    
  # Effect Rules
  rules:
    - rule_id: "enhancement_effect_calculation"
      rule_name: "Enhancement Effect Calculation"
      rule_name_vi: "Tính Toán Hiệu Ứng Tăng Cường"
      rule_type: "enhancement_calculation"
      rule_description: "Calculate enhancement effect properties based on status magnitude and enhancement value"
      rule_formula: "enhancement_intensity = base_intensity * status_magnitude * enhancement_value_multiplier"
      
    - rule_id: "enhancement_effect_application"
      rule_name: "Enhancement Effect Application"
      rule_name_vi: "Áp Dụng Hiệu Ứng Tăng Cường"
      rule_type: "enhancement_application"
      rule_description: "Apply enhancement effects to status visual representation"
      rule_formula: "enhancement_effect = enhancement_system * enhancement_intensity * enhancement_value"
      
    - rule_id: "enhancement_effect_animation"
      rule_name: "Enhancement Effect Animation"
      rule_name_vi: "Hoạt Hình Hiệu Ứng Tăng Cường"
      rule_type: "enhancement_animation"
      rule_description: "Animate enhancement effects over time"
      rule_formula: "enhancement_animation = enhancement_effect * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "enhancement_intensity_multiplier"
      modifier_name: "Enhancement Intensity Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cường Độ Tăng Cường"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "enhancement_value_multiplier"
      modifier_name: "Enhancement Value Multiplier"
      modifier_name_vi: "Hệ Số Nhân Giá Trị Tăng Cường"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "enhancement_effect_with_healing"
      interaction_name: "Enhancement Effect with Healing"
      interaction_name_vi: "Hiệu Ứng Tăng Cường với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_visual_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "enhancement_effect_with_resistance"
      interaction_name: "Enhancement Effect with Resistance"
      interaction_name_vi: "Hiệu Ứng Tăng Cường với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_visual_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "enhancement_effect_immunity"
      immunity_name: "Enhancement Effect Immunity"
      immunity_name_vi: "Miễn Nhiễm Hiệu Ứng Tăng Cường"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "enhancement_effect_indicator"
      effect_name: "Enhancement Effect Indicator"
      effect_name_vi: "Chỉ Báo Hiệu Ứng Tăng Cường"
      effect_type: "indicator_effect"
      indicator_type: "enhancement"
      indicator_color: "#ffd700"
      indicator_intensity: 0.8
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "enhancement_effect_sound"
      effect_name: "Enhancement Effect Sound"
      effect_name_vi: "Âm Thanh Hiệu Ứng Tăng Cường"
      effect_type: "ambient_sound"
      sound_type: "enhancement"
      volume: 0.6
      loop: true
