# Immunity Effect Visual Effect Configuration
visual_effect_definition:
  # Basic Info
  effect_id: "immunity_effect"
  effect_name: "Immunity Effect"
  effect_name_vi: "Hiệu Ứng Miễn Nhiễm"
  
  # Effect Properties
  effect_type: "immunity"
  priority: 200
  stackable: false
  max_stacks: 1
  stack_behavior: "replace_all"
  
  # Effect Description
  description: "Creates immunity effects for status visual representation"
  description_vi: "Tạo hiệu ứng miễn nhiễm cho biểu diễn trực quan của trạng thái"
  
  # Effect Properties
  properties:
    immunity_type: "complete"
    immunity_color: "#ffd700"
    immunity_intensity: 1.0
    immunity_duration: "permanent"
    immunity_size: 1.0
    immunity_rotation: false
    immunity_pulse: false
    immunity_fade: false
    immunity_loop: false
    visual_effect: "immunity_effect_indicator"
    audio_effect: "immunity_effect_sound"
    
  # Effect Rules
  rules:
    - rule_id: "immunity_effect_calculation"
      rule_name: "Immunity Effect Calculation"
      rule_name_vi: "Tính Toán Hiệu Ứng Miễn Nhiễm"
      rule_type: "immunity_calculation"
      rule_description: "Calculate immunity effect properties based on status magnitude and immunity type"
      rule_formula: "immunity_intensity = base_intensity * status_magnitude * immunity_type_multiplier"
      
    - rule_id: "immunity_effect_application"
      rule_name: "Immunity Effect Application"
      rule_name_vi: "Áp Dụng Hiệu Ứng Miễn Nhiễm"
      rule_type: "immunity_application"
      rule_description: "Apply immunity effects to status visual representation"
      rule_formula: "immunity_effect = immunity_system * immunity_intensity * immunity_duration"
      
    - rule_id: "immunity_effect_animation"
      rule_name: "Immunity Effect Animation"
      rule_name_vi: "Hoạt Hình Hiệu Ứng Miễn Nhiễm"
      rule_type: "immunity_animation"
      rule_description: "Animate immunity effects over time"
      rule_formula: "immunity_animation = immunity_effect * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "immunity_intensity_multiplier"
      modifier_name: "Immunity Intensity Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cường Độ Miễn Nhiễm"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "element_mastery"
      
    - modifier_id: "immunity_duration_multiplier"
      modifier_name: "Immunity Duration Multiplier"
      modifier_name_vi: "Hệ Số Nhân Thời Lượng Miễn Nhiễm"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "constitution"
      
  # Effect Interactions
  interactions:
    - interaction_id: "immunity_effect_with_healing"
      interaction_name: "Immunity Effect with Healing"
      interaction_name_vi: "Hiệu Ứng Miễn Nhiễm với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_visual_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.0
      
    - interaction_id: "immunity_effect_with_resistance"
      interaction_name: "Immunity Effect with Resistance"
      interaction_name_vi: "Hiệu Ứng Miễn Nhiễm với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_visual_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.0
      
  # Effect Immunity
  immunity:
    - immunity_id: "immunity_effect_immunity"
      immunity_name: "Immunity Effect Immunity"
      immunity_name_vi: "Miễn Nhiễm Hiệu Ứng Miễn Nhiễm"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "immunity_effect_indicator"
      effect_name: "Immunity Effect Indicator"
      effect_name_vi: "Chỉ Báo Hiệu Ứng Miễn Nhiễm"
      effect_type: "indicator_effect"
      indicator_type: "immunity"
      indicator_color: "#ffd700"
      indicator_intensity: 1.0
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "immunity_effect_sound"
      effect_name: "Immunity Effect Sound"
      effect_name_vi: "Âm Thanh Hiệu Ứng Miễn Nhiễm"
      effect_type: "instant_sound"
      sound_type: "immunity"
      volume: 0.9
      loop: false
