# Resistance Effect Visual Effect Configuration
visual_effect_definition:
  # Basic Info
  effect_id: "resistance_effect"
  effect_name: "Resistance Effect"
  effect_name_vi: "Hiệu Ứng Kháng Cự"
  
  # Effect Properties
  effect_type: "resistance"
  priority: 160
  stackable: true
  max_stacks: 8
  stack_behavior: "stack_additive"
  
  # Effect Description
  description: "Creates resistance effects for status visual representation"
  description_vi: "Tạo hiệu ứng kháng cự cho biểu diễn trực quan của trạng thái"
  
  # Effect Properties
  properties:
    resistance_type: "damage_reduction"
    resistance_color: "#4ecdc4"
    resistance_intensity: 0.7
    resistance_value: 0.7
    resistance_size: 0.8
    resistance_rotation: true
    resistance_pulse: true
    resistance_fade: true
    resistance_loop: true
    visual_effect: "resistance_effect_indicator"
    audio_effect: "resistance_effect_sound"
    
  # Effect Rules
  rules:
    - rule_id: "resistance_effect_calculation"
      rule_name: "Resistance Effect Calculation"
      rule_name_vi: "Tính Toán Hiệu Ứng Kháng Cự"
      rule_type: "resistance_calculation"
      rule_description: "Calculate resistance effect properties based on status magnitude and resistance value"
      rule_formula: "resistance_intensity = base_intensity * status_magnitude * resistance_value_multiplier"
      
    - rule_id: "resistance_effect_application"
      rule_name: "Resistance Effect Application"
      rule_name_vi: "Áp Dụng Hiệu Ứng Kháng Cự"
      rule_type: "resistance_application"
      rule_description: "Apply resistance effects to status visual representation"
      rule_formula: "resistance_effect = resistance_system * resistance_intensity * resistance_value"
      
    - rule_id: "resistance_effect_animation"
      rule_name: "Resistance Effect Animation"
      rule_name_vi: "Hoạt Hình Hiệu Ứng Kháng Cự"
      rule_type: "resistance_animation"
      rule_description: "Animate resistance effects over time"
      rule_formula: "resistance_animation = resistance_effect * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "resistance_intensity_multiplier"
      modifier_name: "Resistance Intensity Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cường Độ Kháng Cự"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "constitution"
      
    - modifier_id: "resistance_value_multiplier"
      modifier_name: "Resistance Value Multiplier"
      modifier_name_vi: "Hệ Số Nhân Giá Trị Kháng Cự"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "resistance_effect_with_healing"
      interaction_name: "Resistance Effect with Healing"
      interaction_name_vi: "Hiệu Ứng Kháng Cự với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_visual_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.3
      
    - interaction_id: "resistance_effect_with_damage"
      interaction_name: "Resistance Effect with Damage"
      interaction_name_vi: "Hiệu Ứng Kháng Cự với Sát Thương"
      interaction_type: "resistance"
      target_effect: "damage_visual_effect"
      interaction_behavior: "reduce_damage"
      interaction_modifier: 0.5
      
  # Effect Immunity
  immunity:
    - immunity_id: "resistance_effect_immunity"
      immunity_name: "Resistance Effect Immunity"
      immunity_name_vi: "Miễn Nhiễm Hiệu Ứng Kháng Cự"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "resistance_effect_indicator"
      effect_name: "Resistance Effect Indicator"
      effect_name_vi: "Chỉ Báo Hiệu Ứng Kháng Cự"
      effect_type: "indicator_effect"
      indicator_type: "resistance"
      indicator_color: "#4ecdc4"
      indicator_intensity: 0.7
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "resistance_effect_sound"
      effect_name: "Resistance Effect Sound"
      effect_name_vi: "Âm Thanh Hiệu Ứng Kháng Cự"
      effect_type: "ambient_sound"
      sound_type: "resistance"
      volume: 0.6
      loop: true
