# Stacking Effect Visual Effect Configuration
visual_effect_definition:
  # Basic Info
  effect_id: "stacking_effect"
  effect_name: "Stacking Effect"
  effect_name_vi: "Hiệu Ứng Chồng Chất"
  
  # Effect Properties
  effect_type: "stacking"
  priority: 110
  stackable: true
  max_stacks: 10
  stack_behavior: "stack_additive"
  
  # Effect Description
  description: "Creates stacking effects for status visual representation"
  description_vi: "Tạo hiệu ứng chồng chất cho biểu diễn trực quan của trạng thái"
  
  # Effect Properties
  properties:
    stacking_type: "additive"
    stacking_color: "#2c1810"
    stacking_intensity: 0.6
    stacking_count: 1
    stacking_size: 0.5
    stacking_rotation: false
    stacking_pulse: false
    stacking_fade: true
    stacking_loop: true
    visual_effect: "stacking_effect_indicator"
    audio_effect: "stacking_effect_sound"
    
  # Effect Rules
  rules:
    - rule_id: "stacking_effect_calculation"
      rule_name: "Stacking Effect Calculation"
      rule_name_vi: "Tính Toán Hiệu Ứng Chồng Chất"
      rule_type: "stacking_calculation"
      rule_description: "Calculate stacking effect properties based on status magnitude and stack count"
      rule_formula: "stacking_intensity = base_intensity * status_magnitude * stack_count_multiplier"
      
    - rule_id: "stacking_effect_application"
      rule_name: "Stacking Effect Application"
      rule_name_vi: "Áp Dụng Hiệu Ứng Chồng Chất"
      rule_type: "stacking_application"
      rule_description: "Apply stacking effects to status visual representation"
      rule_formula: "stacking_effect = stacking_system * stacking_intensity * stacking_count"
      
    - rule_id: "stacking_effect_animation"
      rule_name: "Stacking Effect Animation"
      rule_name_vi: "Hoạt Hình Hiệu Ứng Chồng Chất"
      rule_type: "stacking_animation"
      rule_description: "Animate stacking effects over time"
      rule_formula: "stacking_animation = stacking_effect * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "stacking_intensity_multiplier"
      modifier_name: "Stacking Intensity Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cường Độ Chồng Chất"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "stacking_count_multiplier"
      modifier_name: "Stacking Count Multiplier"
      modifier_name_vi: "Hệ Số Nhân Số Lượng Chồng Chất"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "stacking_effect_with_healing"
      interaction_name: "Stacking Effect with Healing"
      interaction_name_vi: "Hiệu Ứng Chồng Chất với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_visual_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "stacking_effect_with_resistance"
      interaction_name: "Stacking Effect with Resistance"
      interaction_name_vi: "Hiệu Ứng Chồng Chất với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_visual_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "stacking_effect_immunity"
      immunity_name: "Stacking Effect Immunity"
      immunity_name_vi: "Miễn Nhiễm Hiệu Ứng Chồng Chất"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "stacking_effect_indicator"
      effect_name: "Stacking Effect Indicator"
      effect_name_vi: "Chỉ Báo Hiệu Ứng Chồng Chất"
      effect_type: "indicator_effect"
      indicator_type: "stacking"
      indicator_color: "#2c1810"
      indicator_intensity: 0.6
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "stacking_effect_sound"
      effect_name: "Stacking Effect Sound"
      effect_name_vi: "Âm Thanh Hiệu Ứng Chồng Chất"
      effect_type: "ambient_sound"
      sound_type: "stacking"
      volume: 0.6
      loop: true
