# Synergy Effect Visual Effect Configuration
visual_effect_definition:
  # Basic Info
  effect_id: "synergy_effect"
  effect_name: "Synergy Effect"
  effect_name_vi: "Hiệu Ứng Hiệp Lực"
  
  # Effect Properties
  effect_type: "synergy"
  priority: 140
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Effect Description
  description: "Creates synergy effects for status visual representation"
  description_vi: "Tạo hiệu ứng hiệp lực cho biểu diễn trực quan của trạng thái"
  
  # Effect Properties
  properties:
    synergy_type: "effectiveness_enhancement"
    synergy_color: "#ffd700"
    synergy_intensity: 0.8
    synergy_value: 0.25
    synergy_size: 0.7
    synergy_rotation: true
    synergy_pulse: true
    synergy_fade: true
    synergy_loop: true
    visual_effect: "synergy_effect_indicator"
    audio_effect: "synergy_effect_sound"
    
  # Effect Rules
  rules:
    - rule_id: "synergy_effect_calculation"
      rule_name: "Synergy Effect Calculation"
      rule_name_vi: "Tính Toán Hiệu Ứng Hiệp Lực"
      rule_type: "synergy_calculation"
      rule_description: "Calculate synergy effect properties based on status magnitude and synergy value"
      rule_formula: "synergy_intensity = base_intensity * status_magnitude * synergy_value_multiplier"
      
    - rule_id: "synergy_effect_application"
      rule_name: "Synergy Effect Application"
      rule_name_vi: "Áp Dụng Hiệu Ứng Hiệp Lực"
      rule_type: "synergy_application"
      rule_description: "Apply synergy effects to status visual representation"
      rule_formula: "synergy_effect = synergy_system * synergy_intensity * synergy_value"
      
    - rule_id: "synergy_effect_animation"
      rule_name: "Synergy Effect Animation"
      rule_name_vi: "Hoạt Hình Hiệu Ứng Hiệp Lực"
      rule_type: "synergy_animation"
      rule_description: "Animate synergy effects over time"
      rule_formula: "synergy_animation = synergy_effect * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "synergy_intensity_multiplier"
      modifier_name: "Synergy Intensity Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cường Độ Hiệp Lực"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "synergy_value_multiplier"
      modifier_name: "Synergy Value Multiplier"
      modifier_name_vi: "Hệ Số Nhân Giá Trị Hiệp Lực"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "synergy_effect_with_healing"
      interaction_name: "Synergy Effect with Healing"
      interaction_name_vi: "Hiệu Ứng Hiệp Lực với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_visual_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "synergy_effect_with_resistance"
      interaction_name: "Synergy Effect with Resistance"
      interaction_name_vi: "Hiệu Ứng Hiệp Lực với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_visual_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "synergy_effect_immunity"
      immunity_name: "Synergy Effect Immunity"
      immunity_name_vi: "Miễn Nhiễm Hiệu Ứng Hiệp Lực"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "synergy_effect_indicator"
      effect_name: "Synergy Effect Indicator"
      effect_name_vi: "Chỉ Báo Hiệu Ứng Hiệp Lực"
      effect_type: "indicator_effect"
      indicator_type: "synergy"
      indicator_color: "#ffd700"
      indicator_intensity: 0.8
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "synergy_effect_sound"
      effect_name: "Synergy Effect Sound"
      effect_name_vi: "Âm Thanh Hiệu Ứng Hiệp Lực"
      effect_type: "ambient_sound"
      sound_type: "synergy"
      volume: 0.6
      loop: true
