# Trigger Effect Visual Effect Configuration
visual_effect_definition:
  # Basic Info
  effect_id: "trigger_effect"
  effect_name: "Trigger Effect"
  effect_name_vi: "Hiệu Ứng Kích Hoạt"
  
  # Effect Properties
  effect_type: "trigger"
  priority: 160
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Effect Description
  description: "Creates trigger effects for status visual representation"
  description_vi: "Tạo hiệu ứng kích hoạt cho biểu diễn trực quan của trạng thái"
  
  # Effect Properties
  properties:
    trigger_type: "timer"
    trigger_color: "#4ecdc4"
    trigger_intensity: 1.0
    trigger_duration: 1.0
    trigger_size: 0.8
    trigger_rotation: true
    trigger_pulse: true
    trigger_fade: true
    trigger_loop: true
    visual_effect: "trigger_effect_indicator"
    audio_effect: "trigger_effect_sound"
    
  # Effect Rules
  rules:
    - rule_id: "trigger_effect_calculation"
      rule_name: "Trigger Effect Calculation"
      rule_name_vi: "Tính Toán Hiệu Ứng Kích Hoạt"
      rule_type: "trigger_calculation"
      rule_description: "Calculate trigger effect properties based on status magnitude and duration"
      rule_formula: "trigger_intensity = base_intensity * status_magnitude * duration_multiplier"
      
    - rule_id: "trigger_effect_application"
      rule_name: "Trigger Effect Application"
      rule_name_vi: "Áp Dụng Hiệu Ứng Kích Hoạt"
      rule_type: "trigger_application"
      rule_description: "Apply trigger effects to status visual representation"
      rule_formula: "trigger_effect = trigger_system * trigger_intensity * trigger_duration"
      
    - rule_id: "trigger_effect_animation"
      rule_name: "Trigger Effect Animation"
      rule_name_vi: "Hoạt Hình Hiệu Ứng Kích Hoạt"
      rule_type: "trigger_animation"
      rule_description: "Animate trigger effects over time"
      rule_formula: "trigger_animation = trigger_effect * time_multiplier * animation_speed"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "trigger_intensity_multiplier"
      modifier_name: "Trigger Intensity Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cường Độ Kích Hoạt"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "trigger_duration_multiplier"
      modifier_name: "Trigger Duration Multiplier"
      modifier_name_vi: "Hệ Số Nhân Thời Lượng Kích Hoạt"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.005
      scaling_stat: "wisdom"
      
  # Effect Interactions
  interactions:
    - interaction_id: "trigger_effect_with_healing"
      interaction_name: "Trigger Effect with Healing"
      interaction_name_vi: "Hiệu Ứng Kích Hoạt với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_visual_effect"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "trigger_effect_with_resistance"
      interaction_name: "Trigger Effect with Resistance"
      interaction_name_vi: "Hiệu Ứng Kích Hoạt với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance_visual_effect"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Effect Immunity
  immunity:
    - immunity_id: "trigger_effect_immunity"
      immunity_name: "Trigger Effect Immunity"
      immunity_name_vi: "Miễn Nhiễm Hiệu Ứng Kích Hoạt"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "trigger_effect_indicator"
      effect_name: "Trigger Effect Indicator"
      effect_name_vi: "Chỉ Báo Hiệu Ứng Kích Hoạt"
      effect_type: "indicator_effect"
      indicator_type: "trigger"
      indicator_color: "#4ecdc4"
      indicator_intensity: 1.0
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "trigger_effect_sound"
      effect_name: "Trigger Effect Sound"
      effect_name_vi: "Âm Thanh Hiệu Ứng Kích Hoạt"
      effect_type: "ambient_sound"
      sound_type: "trigger"
      volume: 0.6
      loop: true
