# Clamp Ranges Configuration
# This file defines the min/max values for clamping different dimensions

ranges:
  # Health dimension
  health:
    min: 0.0
    max: 10000.0
  
  # Mana dimension
  mana:
    min: 0.0
    max: 5000.0
  
  # Stamina dimension
  stamina:
    min: 0.0
    max: 10000.0
  
  # Strength stat
  strength:
    min: 0.0
    max: 1000.0
  
  # Agility stat
  agility:
    min: 0.0
    max: 1000.0
  
  # Intelligence stat
  intelligence:
    min: 0.0
    max: 1000.0
  
  # Constitution stat
  constitution:
    min: 0.0
    max: 1000.0
  
  # Wisdom stat
  wisdom:
    min: 0.0
    max: 1000.0
  
  # Charisma stat
  charisma:
    min: 0.0
    max: 1000.0
  
  # Element affinities (0.0 to 1.0)
  fire_affinity:
    min: 0.0
    max: 1.0
  
  water_affinity:
    min: 0.0
    max: 1.0
  
  earth_affinity:
    min: 0.0
    max: 1.0
  
  air_affinity:
    min: 0.0
    max: 1.0
  
  light_affinity:
    min: 0.0
    max: 1.0
  
  dark_affinity:
    min: 0.0
    max: 1.0
  
  # Cultivation resources
  qi_capacity:
    min: 0.0
    max: 1000000.0
  
  qi_regen:
    min: 0.0
    max: 1000.0
  
  spiritual_power:
    min: 0.0
    max: 10000.0
  
  body_refinement:
    min: 0.0
    max: 10000.0
  
  mental_defense:
    min: 0.0
    max: 10000.0
  
  hp_max:
    min: 0.0
    max: 100000.0
