# Validation Rules Configuration
# This file defines validation ranges for different value types

resource_values:
  min: 0.0
  max: 1000000.0

stat_values:
  min: 0.0
  max: 1000.0

element_affinities:
  min: 0.0
  max: 1.0

contribution_values:
  min: -1000.0
  max: 1000.0
