# lightning_element.yaml (stub)
version: 1

element:
  id: "lightning"
  name: "Lightning"
  aliases:
    vi: "lôi"
    zh_pinyin: "lei"
  category: "extended_elements"
  description: "Lightning, burst, chain, paralyze risk-reward"

  base_properties:
    base_damage: 110.0
    base_defense: 85.0
    base_crit_rate: 0.16
    base_crit_damage: 1.55
    base_accuracy: 0.9

  affinities:
    fire: 0.4
    water: 0.1
    wood: 0.3
    metal: 0.2
    earth: 0.0

  probability_overrides: {}

  derived_stats:
    # Core Element Mastery
    - "element_mastery"
    
    # Counterbalance Pairs (from lightning_element.yaml)
    - "power_point"
    - "defense_point"
    - "crit_rate"
    - "resist_crit_rate"
    - "crit_damage"
    - "resist_crit_damage"
    - "accurate_rate"
    - "dodge_rate"
    - "status_probability"
    - "status_resistance"
    - "status_duration"
    - "status_duration_reduction"
    - "status_intensity"
    - "status_intensity_reduction"
    - "element_penetration"
    - "element_absorption"
    - "element_amplification"
    - "element_reduction"
    - "reflection_rate"
    - "resist_reflection_rate"
    - "reflection_damage"
    - "resist_reflection_damage"
    
    # Parry System (from lightning_element.yaml)
    - "parry_rate"
    - "parry_break"
    - "parry_strength"
    - "parry_shred"
    
    # Block System (from lightning_element.yaml)
    - "block_rate"
    - "block_break"
    - "block_strength"
    - "block_shred"
    
    # Skill Execution & Performance (from lightning_element.yaml)
    - "skill_execution_speed"
    - "skill_cooldown_reduction"
    - "attack_skill_effectiveness"
    - "defense_skill_effectiveness"
    - "status_skill_effectiveness"
    - "movement_technique_effectiveness"
    - "healing_skill_effectiveness"
    - "support_skill_effectiveness"
    - "utility_skill_effectiveness"
    - "skill_effectiveness"
    
    # Resource Management (from lightning_element.yaml)
    - "resource_regeneration"
    - "resource_efficiency"
    
    # Social & Economy (Future features)
    - "element_leadership_bonus"
    - "element_teaching_efficiency"
    - "element_crafting_efficiency"
    - "element_resource_discovery"
    
    # Perception & Detection
    - "element_sensitivity"
    
    # Advanced Combat Mechanics
    - "mastery_synergy_bonus"
    
    # Element Interaction Bonuses (from Element Interaction System)
    - "element_interaction_bonuses"
    
    # Feature flags for conditional stats
    - "feature_flags"

  status_effects:
    - name: "shocked"
      type: "debuff"
      base_probability: 0.14
      base_duration: 5.0
      base_intensity: 1.0
      tick_interval: 1.0
      max_stacks: 5
      stackable: true
      refresh_duration: true
      effects:
        paralyze_micro: true
        damage_taken_amp: 0.04
      dynamics:
        intensity_gain: 0.016
        intensity_damping: 0.013
        decay_rate: 0.05
        refractory_gain: 0.45
        refractory_decay: 0.12

  same_element_effects:
    - pool_id: "arc_resonance"
      apply_to: "both"
    - pool_id: "overcharge_boost"
      apply_to: "attacker"

  neutral_effects:
    - pool_id: "shocked_fallback"
      apply_to: "defender"
      probability:
        base: "from_element"
        use_probability_engine: true
        scaling_factor_key: "status_probability"
      dynamics_override: {}

references:
  probability_config_path: "../../configs/probability_config.yaml"
  interaction_config_path: "../../configs/interaction_config.yaml"
  status_pool_path: "../../configs/status_pool.yaml"
  dynamics_design: "../../11_Advanced_Derived_Stats_Design.md"
  golden_vectors_path: "../golden_vectors/lightning_golden_vectors.json"

