# metal_element.yaml (stub)
version: 1

element:
  id: "metal"
  name: "Metal"
  aliases:
    vi: "kim"
    zh_pinyin: "jin"
  category: "five_elements"
  description: "Metal, sharpness, resilience, discipline"

  base_properties:
    base_damage: 105.0
    base_defense: 95.0
    base_crit_rate: 0.14
    base_crit_damage: 1.5
    base_accuracy: 0.9

  probability_overrides: {}

  derived_stats:
    # Counterbalance pairs first
    - "power_point"
    - "defense_point"
    - "crit_rate"
    - "resist_crit_rate"
    - "crit_damage"
    - "resist_crit_damage"
    - "accurate_rate"
    - "dodge_rate"
    - "status_probability"
    - "status_resistance"
    - "status_duration"
    - "status_duration_reduction"
    - "status_intensity"
    - "status_intensity_reduction"
    - "element_penetration"
    - "element_absorption"
    - "element_amplification"
    - "element_reduction"
    - "reflection_rate"
    - "resist_reflection_rate"
    - "reflection_damage"
    - "resist_reflection_damage"
    - "parry_rate"
    - "parry_break"
    - "parry_strength"
    - "parry_shred"
    - "block_rate"
    - "block_break"
    - "block_strength"
    - "block_shred"
    - "skill_execution_speed"
    - "skill_cooldown_reduction"
    # Unpaired / type-specific below
    - "combat_skill_effectiveness"
    - "status_skill_effectiveness"
    - "movement_technique_effectiveness"
    - "healing_skill_effectiveness"
    - "skill_effectiveness"
    - "element_reflection"
    - "resource_regeneration"
    - "resource_efficiency"
    - "element_resource_discovery"
    - "element_sensitivity"

  status_effects:
    - name: "brittle"
      type: "debuff"
      base_probability: 0.1
      base_duration: 6.0
      base_intensity: 1.0
      tick_interval: 1.0
      max_stacks: 5
      stackable: true
      refresh_duration: true
      effects:
        defense_reduction: 0.05
      dynamics:
        intensity_gain: 0.014
        intensity_damping: 0.012
        decay_rate: 0.04
        refractory_gain: 0.35
        refractory_decay: 0.1

  same_element_effects:
    - pool_id: "temper_resonance"
      apply_to: "both"

  neutral_effects:
    - pool_id: "brittle_fallback"
      apply_to: "defender"
      probability:
        base: "from_element"
        use_probability_engine: true
        scaling_factor_key: "status_probability"
      dynamics_override: {}

references:
  probability_config_path: "../../configs/probability_config.yaml"
  interaction_config_path: "../../configs/interaction_config.yaml"
  status_pool_path: "../../configs/status_pool.yaml"
  dynamics_design: "../../11_Advanced_Derived_Stats_Design.md"
  golden_vectors_path: "../golden_vectors/metal_golden_vectors.json"

