# water_element.yaml (stub)
version: 1

element:
  id: "water"
  name: "Water"
  aliases:
    vi: "thủy"
    zh_pinyin: "shui"
  category: "five_elements"
  description: "Water, fluid, adaptable, control"

  base_properties:
    base_damage: 90.0
    base_defense: 90.0
    base_crit_rate: 0.12
    base_crit_damage: 1.4
    base_accuracy: 0.90

  probability_overrides: {}

  derived_stats:
    # Core Element Mastery
    - "element_mastery"
    
    # Counterbalance Pairs (from water_element.yaml)
    - "power_point"
    - "defense_point"
    - "crit_rate"
    - "resist_crit_rate"
    - "crit_damage"
    - "resist_crit_damage"
    - "accurate_rate"
    - "dodge_rate"
    - "status_probability"
    - "status_resistance"
    - "status_duration"
    - "status_duration_reduction"
    - "status_intensity"
    - "status_intensity_reduction"
    - "element_penetration"
    - "element_absorption"
    - "element_amplification"
    - "element_reduction"
    - "reflection_rate"
    - "resist_reflection_rate"
    - "reflection_damage"
    - "resist_reflection_damage"
    
    # Parry System (from water_element.yaml)
    - "parry_rate"
    - "parry_break"
    - "parry_strength"
    - "parry_shred"
    
    # Block System (from water_element.yaml)
    - "block_rate"
    - "block_break"
    - "block_strength"
    - "block_shred"
    
    # Skill Execution & Performance (from water_element.yaml)
    - "skill_execution_speed"
    - "skill_cooldown_reduction"
    - "attack_skill_effectiveness"
    - "defense_skill_effectiveness"
    - "status_skill_effectiveness"
    - "movement_technique_effectiveness"
    - "healing_skill_effectiveness"
    - "support_skill_effectiveness"
    - "utility_skill_effectiveness"
    - "skill_effectiveness"
    
    # Resource Management (from water_element.yaml)
    - "resource_regeneration"
    - "resource_efficiency"
    
    # Social & Economy (Future features)
    - "element_leadership_bonus"
    - "element_teaching_efficiency"
    - "element_crafting_efficiency"
    - "element_resource_discovery"
    
    # Perception & Detection
    - "element_sensitivity"
    
    # Advanced Combat Mechanics
    - "mastery_synergy_bonus"
    
    # Element Interaction Bonuses (from Element Interaction System)
    - "element_interaction_bonuses"
    
    # Feature flags for conditional stats
    - "feature_flags"

  status_effects:
    - name: "soaked"
      type: "debuff"
      base_probability: 0.12
      base_duration: 6.0
      base_intensity: 1.0
      tick_interval: 1.0
      max_stacks: 5
      stackable: true
      refresh_duration: true
      spread_rules:
        enabled: true
        spread_chance_base: 0.04
        spread_range: 2.5
        spread_max_targets: 2
      effects:
        move_speed_slow: 0.08      # 8% per intensity unit (subject to engine hook)
        accurate_rate_debuff: 0.04 # 4% per intensity unit
      dynamics:
        intensity_gain: 0.015
        intensity_damping: 0.012
        decay_rate: 0.04
        refractory_gain: 0.4
        refractory_decay: 0.1

  same_element_effects:
    - pool_id: "flow_resonance"
      apply_to: "both"
    - pool_id: "aqua_veil"
      apply_to: "defender"

  neutral_effects:
    - pool_id: "soaked_fallback"
      apply_to: "defender"
      probability:
        base: "from_element"
        use_probability_engine: true
        scaling_factor_key: "status_probability"
      dynamics_override: {}

  environment_mods:
    rain:
      status_probability_add: +0.05
      intensity_gain_mod: +0.005
    dry:
      status_probability_add: -0.05
      intensity_gain_mod: -0.005

references:
  probability_config_path: "../../configs/probability_config.yaml"
  interaction_config_path: "../../configs/interaction_config.yaml"
  status_pool_path: "../../configs/status_pool.yaml"
  dynamics_design: "../../11_Advanced_Derived_Stats_Design.md"
  golden_vectors_path: "../golden_vectors/water_golden_vectors.json"

