# wood_element.yaml (stub)
version: 1

element:
  id: "wood"
  name: "Wood"
  aliases:
    vi: "mộc"
    zh_pinyin: "mu"
  category: "five_elements"
  description: "Wood, growth, flexibility, sustain"

  base_properties:
    base_damage: 95.0
    base_defense: 85.0
    base_crit_rate: 0.13
    base_crit_damage: 1.45
    base_accuracy: 0.88

  probability_overrides: {}

  derived_stats:
    - "power_point"
    - "defense_point"
    - "crit_rate"
    - "crit_damage"
    - "accurate_rate"
    - "dodge_rate"
    - "status_probability"
    - "status_duration"
    - "status_intensity"
    - "status_resistance"
    - "status_duration_reduction"
    - "status_intensity_reduction"

  status_effects:
    - name: "entangled"
      type: "debuff"
      base_probability: 0.1
      base_duration: 6.0
      base_intensity: 1.0
      tick_interval: 1.0
      max_stacks: 5
      stackable: true
      refresh_duration: true
      effects:
        move_speed_slow: 0.06
      dynamics:
        intensity_gain: 0.014
        intensity_damping: 0.012
        decay_rate: 0.04
        refractory_gain: 0.35
        refractory_decay: 0.1

  same_element_effects:
    - pool_id: "growth_resonance"
      apply_to: "both"
    - pool_id: "bark_ward"
      apply_to: "defender"

  neutral_effects:
    - pool_id: "entangle_fallback"
      apply_to: "defender"
      probability:
        base: "from_element"
        use_probability_engine: true
        scaling_factor_key: "status_probability"
      dynamics_override: {}

references:
  probability_config_path: "../../configs/probability_config.yaml"
  interaction_config_path: "../../configs/interaction_config.yaml"
  status_pool_path: "../../configs/status_pool.yaml"
  dynamics_design: "../../11_Advanced_Derived_Stats_Design.md"
  golden_vectors_path: "../golden_vectors/wood_golden_vectors.json"

