# On Action Execution Trigger Configuration
trigger_definition:
  # Basic Info
  trigger_id: "on_action_execution"
  trigger_name: "On Action Execution"
  trigger_name_vi: "Khi Thực Hiện Hành Động"
  
  # Trigger Properties
  trigger_type: "action_execution"
  priority: 150
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Trigger Description
  description: "Trigger when actor performs specific actions"
  description_vi: "Kích hoạt khi diễn viên thực hiện hành động cụ thể"
  
  # Trigger Properties
  properties:
    action_categories: ["physical", "movement", "attack", "defense"]
    execution_type: "any"
    visual_effect: "action_execution_trigger"
    audio_effect: "action_execution_trigger_sound"
    
  # Trigger Rules
  rules:
    - rule_id: "action_execution_trigger_calculation"
      rule_name: "Action Execution Trigger Calculation"
      rule_name_vi: "Tính Toán Kích Hoạt Thực Hiện Hành Động"
      rule_type: "trigger_calculation"
      rule_description: "Calculate action execution trigger based on action categories"
      rule_formula: "action_trigger = action_executed && action_category in required_categories"
      
    - rule_id: "action_execution_effect_processing"
      rule_name: "Action Execution Effect Processing"
      rule_name_vi: "Xử Lý Hiệu Ứng Thực Hiện Hành Động"
      rule_type: "effect_processing"
      rule_description: "Process effects when action execution trigger is activated"
      rule_formula: "effect_processed = action_trigger && effect_conditions_met"
      
    - rule_id: "action_execution_immediate_application"
      rule_name: "Action Execution Immediate Application"
      rule_name_vi: "Áp Dụng Tức Thời Thực Hiện Hành Động"
      rule_type: "immediate_application"
      rule_description: "Apply effects immediately when action execution trigger is activated"
      rule_formula: "immediate_applied = action_trigger && execution_type == any"
      
  # Trigger Modifiers
  modifiers:
    - modifier_id: "action_execution_multiplier"
      modifier_name: "Action Execution Multiplier"
      modifier_name_vi: "Hệ Số Nhân Thực Hiện Hành Động"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
    - modifier_id: "action_execution_modifier"
      modifier_name: "Action Execution Modifier"
      modifier_name_vi: "Sửa Đổi Thực Hiện Hành Động"
      modifier_type: "execution"
      base_value: 0.0
      scaling_factor: 0.01
      scaling_stat: "constitution"
      
  # Trigger Interactions
  interactions:
    - interaction_id: "action_execution_with_healing"
      interaction_name: "Action Execution with Healing"
      interaction_name_vi: "Thực Hiện Hành Động với Hồi Máu"
      interaction_type: "conflict"
      target_trigger: "healing_trigger"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "action_execution_with_resistance"
      interaction_name: "Action Execution with Resistance"
      interaction_name_vi: "Thực Hiện Hành Động với Kháng Cự"
      interaction_type: "resistance"
      target_trigger: "resistance_trigger"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Trigger Immunity
  immunity:
    - immunity_id: "action_execution_immunity"
      immunity_name: "Action Execution Immunity"
      immunity_name_vi: "Miễn Nhiễm Thực Hiện Hành Động"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Trigger Visual Effects
  visual_effects:
    - effect_id: "action_execution_trigger"
      effect_name: "Action Execution Trigger"
      effect_name_vi: "Kích Hoạt Thực Hiện Hành Động"
      effect_type: "trigger_effect"
      trigger_type: "action"
      trigger_color: "#45b7d1"
      trigger_intensity: 1.0
      
  # Trigger Audio Effects
  audio_effects:
    - effect_id: "action_execution_trigger_sound"
      effect_name: "Action Execution Trigger Sound"
      effect_name_vi: "Âm Thanh Kích Hoạt Thực Hiện Hành Động"
      effect_type: "ambient_sound"
      sound_type: "action"
      volume: 0.7
      loop: true
