# On Healing Received Trigger Configuration
trigger_definition:
  # Basic Info
  trigger_id: "on_healing_received"
  trigger_name: "On Healing Received"
  trigger_name_vi: "Khi Nhận Hồi Máu"
  
  # Trigger Properties
  trigger_type: "healing_received"
  priority: 170
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Trigger Description
  description: "Trigger when actor receives healing from specific sources"
  description_vi: "Kích hoạt khi diễn viên nhận hồi máu từ nguồn cụ thể"
  
  # Trigger Properties
  properties:
    healing_types: ["life_energy", "magical", "potion"]
    healing_source: "any"
    visual_effect: "healing_received_trigger"
    audio_effect: "healing_received_trigger_sound"
    
  # Trigger Rules
  rules:
    - rule_id: "healing_received_trigger_calculation"
      rule_name: "Healing Received Trigger Calculation"
      rule_name_vi: "Tính Toán Kích Hoạt Nhận Hồi Máu"
      rule_type: "trigger_calculation"
      rule_description: "Calculate healing received trigger based on healing types and sources"
      rule_formula: "healing_trigger = healing_received && healing_type in required_types"
      
    - rule_id: "healing_received_effect_processing"
      rule_name: "Healing Received Effect Processing"
      rule_name_vi: "Xử Lý Hiệu Ứng Nhận Hồi Máu"
      rule_type: "effect_processing"
      rule_description: "Process effects when healing received trigger is activated"
      rule_formula: "effect_processed = healing_trigger && effect_conditions_met"
      
    - rule_id: "healing_received_immediate_application"
      rule_name: "Healing Received Immediate Application"
      rule_name_vi: "Áp Dụng Tức Thời Nhận Hồi Máu"
      rule_type: "immediate_application"
      rule_description: "Apply effects immediately when healing received trigger is activated"
      rule_formula: "immediate_applied = healing_trigger && healing_source == any"
      
  # Trigger Modifiers
  modifiers:
    - modifier_id: "healing_received_multiplier"
      modifier_name: "Healing Received Multiplier"
      modifier_name_vi: "Hệ Số Nhân Nhận Hồi Máu"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "wisdom"
      
    - modifier_id: "healing_received_modifier"
      modifier_name: "Healing Received Modifier"
      modifier_name_vi: "Sửa Đổi Nhận Hồi Máu"
      modifier_type: "healing"
      base_value: 0.0
      scaling_factor: 0.01
      scaling_stat: "constitution"
      
  # Trigger Interactions
  interactions:
    - interaction_id: "healing_received_with_damage"
      interaction_name: "Healing Received with Damage"
      interaction_name_vi: "Nhận Hồi Máu với Sát Thương"
      interaction_type: "conflict"
      target_trigger: "damage_trigger"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.7
      
    - interaction_id: "healing_received_with_resistance"
      interaction_name: "Healing Received with Resistance"
      interaction_name_vi: "Nhận Hồi Máu với Kháng Cự"
      interaction_type: "resistance"
      target_trigger: "resistance_trigger"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.5
      
  # Trigger Immunity
  immunity:
    - immunity_id: "healing_received_immunity"
      immunity_name: "Healing Received Immunity"
      immunity_name_vi: "Miễn Nhiễm Nhận Hồi Máu"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Trigger Visual Effects
  visual_effects:
    - effect_id: "healing_received_trigger"
      effect_name: "Healing Received Trigger"
      effect_name_vi: "Kích Hoạt Nhận Hồi Máu"
      effect_type: "trigger_effect"
      trigger_type: "healing"
      trigger_color: "#ffd700"
      trigger_intensity: 0.8
      
  # Trigger Audio Effects
  audio_effects:
    - effect_id: "healing_received_trigger_sound"
      effect_name: "Healing Received Trigger Sound"
      effect_name_vi: "Âm Thanh Kích Hoạt Nhận Hồi Máu"
      effect_type: "instant_sound"
      sound_type: "healing"
      volume: 0.5
      loop: false
