# Environment Condition Configuration
condition_definition:
  # Basic Info
  condition_id: "environment_condition"
  condition_name: "Environment Condition"
  condition_name_vi: "Điều Kiện Môi Trường"
  
  # Condition Properties
  condition_type: "environment"
  priority: 160
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Condition Description
  description: "Condition based on environment type and conditions"
  description_vi: "Điều kiện dựa trên loại môi trường và điều kiện"
  
  # Condition Properties
  properties:
    environment_type: "combat"
    environment_value: "active"
    condition_type: "environment_match"
    visual_effect: "environment_indicator"
    audio_effect: "environment_sound"
    
  # Condition Rules
  rules:
    - rule_id: "environment_type_check"
      rule_name: "Environment Type Check"
      rule_name_vi: "Kiểm Tra Loại Môi Trường"
      rule_type: "type_check"
      rule_description: "Check if environment matches required type"
      rule_formula: "environment_check = current_environment == required_environment"
      
    - rule_id: "environment_value_check"
      rule_name: "Environment Value Check"
      rule_name_vi: "Kiểm Tra Giá Trị Môi Trường"
      rule_type: "value_check"
      rule_description: "Check if environment value meets requirements"
      rule_formula: "value_check = environment_value condition_type required_value"
      
    - rule_id: "environment_condition_processing"
      rule_name: "Environment Condition Processing"
      rule_name_vi: "Xử Lý Điều Kiện Môi Trường"
      rule_type: "condition_processing"
      rule_description: "Process environment condition and trigger effects"
      rule_formula: "condition_trigger = environment_check && value_check"
      
  # Condition Modifiers
  modifiers:
    - modifier_id: "environment_type_multiplier"
      modifier_name: "Environment Type Multiplier"
      modifier_name_vi: "Hệ Số Nhân Loại Môi Trường"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "wisdom"
      
    - modifier_id: "environment_value_modifier"
      modifier_name: "Environment Value Modifier"
      modifier_name_vi: "Sửa Đổi Giá Trị Môi Trường"
      modifier_type: "value"
      base_value: 0.0
      scaling_factor: 0.01
      scaling_stat: "intelligence"
      
  # Condition Interactions
  interactions:
    - interaction_id: "environment_with_healing"
      interaction_name: "Environment with Healing"
      interaction_name_vi: "Môi Trường với Hồi Máu"
      interaction_type: "conflict"
      target_condition: "healing_condition"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "environment_with_resistance"
      interaction_name: "Environment with Resistance"
      interaction_name_vi: "Môi Trường với Kháng Cự"
      interaction_type: "resistance"
      target_condition: "resistance_condition"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Condition Immunity
  immunity:
    - immunity_id: "environment_immunity"
      immunity_name: "Environment Immunity"
      immunity_name_vi: "Miễn Nhiễm Môi Trường"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Condition Visual Effects
  visual_effects:
    - effect_id: "environment_indicator"
      effect_name: "Environment Indicator"
      effect_name_vi: "Chỉ Báo Môi Trường"
      effect_type: "indicator_effect"
      indicator_type: "environment"
      indicator_color: "#96ceb4"
      indicator_intensity: 0.8
      
  # Condition Audio Effects
  audio_effects:
    - effect_id: "environment_sound"
      effect_name: "Environment Sound"
      effect_name_vi: "Âm Thanh Môi Trường"
      effect_type: "ambient_sound"
      sound_type: "environment"
      volume: 0.6
      loop: true
