# Damage On Action Effect Configuration
effect_definition:
  # Basic Info
  effect_id: "damage_on_action"
  effect_name: "Damage On Action"
  effect_name_vi: "Sát Thương Khi Hành Động"
  
  # Effect Properties
  effect_type: "damage"
  priority: 180
  stackable: false
  max_stacks: 1
  stack_behavior: "replace_all"
  
  # Effect Description
  description: "Deals damage when actor performs specific actions based on magnitude and scaling factors"
  description_vi: "Gây sát thương khi diễn viên thực hiện hành động cụ thể dựa trên cường độ và hệ số nhân"
  
  # Effect Properties
  properties:
    damage_type: "physical"
    damage_source: "status_effect"
    visual_effect: "damage_particles"
    audio_effect: "damage_sound"
    element_binding: true
    resistance_calculation: true
    
  # Effect Rules
  rules:
    - rule_id: "damage_on_action_calculation"
      rule_name: "Damage On Action Calculation"
      rule_name_vi: "Tính Toán Sát Thương Khi Hành Động"
      rule_type: "damage_calculation"
      rule_description: "Calculate damage when action is performed based on magnitude and scaling factors"
      rule_formula: "damage = base_magnitude * scaling_factor * action_intensity"
      
    - rule_id: "damage_on_action_duration"
      rule_name: "Damage On Action Duration"
      rule_name_vi: "Thời Gian Sát Thương Khi Hành Động"
      rule_type: "duration_calculation"
      rule_description: "Calculate effect duration based on mastery and resistance"
      rule_formula: "duration = base_duration * (1 + mastery_bonus - resistance_modifier)"
      
    - rule_id: "damage_on_action_trigger"
      rule_name: "Damage On Action Trigger"
      rule_name_vi: "Kích Hoạt Sát Thương Khi Hành Động"
      rule_type: "trigger_calculation"
      rule_description: "Calculate damage trigger based on action category and intensity"
      rule_formula: "trigger_damage = base_damage * action_category_modifier * action_intensity"
      
  # Effect Modifiers
  modifiers:
    - modifier_id: "damage_magnitude_multiplier"
      modifier_name: "Damage Magnitude Multiplier"
      modifier_name_vi: "Hệ Số Nhân Cường Độ Sát Thương"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "constitution"
      
    - modifier_id: "damage_resistance_modifier"
      modifier_name: "Damage Resistance Modifier"
      modifier_name_vi: "Sửa Đổi Kháng Sát Thương"
      modifier_type: "resistance"
      base_value: 0.0
      scaling_factor: 0.01
      scaling_stat: "strength"
      
  # Effect Interactions
  interactions:
    - interaction_id: "damage_on_action_with_healing"
      interaction_name: "Damage On Action with Healing"
      interaction_name_vi: "Sát Thương Khi Hành Động với Hồi Máu"
      interaction_type: "conflict"
      target_effect: "healing_over_time"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.7
      
    - interaction_id: "damage_on_action_with_resistance"
      interaction_name: "Damage On Action with Resistance"
      interaction_name_vi: "Sát Thương Khi Hành Động với Kháng Cự"
      interaction_type: "resistance"
      target_effect: "resistance"
      interaction_behavior: "reduce_damage"
      interaction_modifier: 0.5
      
  # Effect Immunity
  immunity:
    - immunity_id: "damage_on_action_immunity"
      immunity_name: "Damage On Action Immunity"
      immunity_name_vi: "Miễn Nhiễm Sát Thương Khi Hành Động"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Effect Visual Effects
  visual_effects:
    - effect_id: "damage_particles"
      effect_name: "Damage Particles"
      effect_name_vi: "Hạt Sát Thương"
      effect_type: "particle_system"
      particle_type: "damage"
      particle_color: "#ff6b35"
      particle_intensity: 1.0
      
  # Effect Audio Effects
  audio_effects:
    - effect_id: "damage_sound"
      effect_name: "Damage Sound"
      effect_name_vi: "Âm Thanh Sát Thương"
      effect_type: "instant_sound"
      sound_type: "damage"
      volume: 0.7
      loop: false
