# Cap Layers Configuration
# Defines the order and configuration of cap layers for actor capabilities

layers:
  - name: "base"
    priority: 100
    caps:
      - id: "health"
        cap_mode: "BASELINE"
        min: 0.0
        max: 1000.0
      - id: "mana"
        cap_mode: "BASELINE"
        min: 0.0
        max: 500.0
        
  - name: "race"
    priority: 90
    caps:
      - id: "health"
        cap_mode: "ADDITIVE"
        min: 0.5
        max: 2.0
      - id: "mana"
        cap_mode: "ADDITIVE"
        min: 0.5
        max: 2.0
        
  - name: "class"
    priority: 80
    caps:
      - id: "health"
        cap_mode: "ADDITIVE"
        min: 0.0
        max: 200.0
      - id: "mana"
        cap_mode: "ADDITIVE"
        min: 0.0
        max: 300.0
        
  - name: "equipment"
    priority: 70
    caps:
      - id: "health"
        cap_mode: "ADDITIVE"
        min: 0.0
        max: 100.0
      - id: "mana"
        cap_mode: "ADDITIVE"
        min: 0.0
        max: 150.0
        
  - name: "buffs"
    priority: 60
    caps:
      - id: "health"
        cap_mode: "ADDITIVE"
        min: 0.1
        max: 3.0
      - id: "mana"
        cap_mode: "ADDITIVE"
        min: 0.1
        max: 3.0
        
  - name: "final"
    priority: 10
    caps:
      - id: "health"
        cap_mode: "HARD_MAX"
        min: 1.0
        max: 9999.0
      - id: "mana"
        cap_mode: "HARD_MAX"
        min: 1.0
        max: 9999.0
