# Conditional Immunity Configuration
immunity_definition:
  # Basic Info
  immunity_id: "conditional_immunity"
  immunity_name: "Conditional Immunity"
  immunity_name_vi: "Miễn Nhiễm Có Điều Kiện"
  
  # Immunity Properties
  immunity_type: "conditional"
  priority: 170
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Immunity Description
  description: "Provides immunity based on specific conditions and circumstances"
  description_vi: "Cung cấp miễn nhiễm dựa trên điều kiện và hoàn cảnh cụ thể"
  
  # Immunity Properties
  properties:
    immunity_condition: "health_above_80%"
    immunity_type: "debuff_status"
    immunity_duration: "conditional"
    immunity_reason: "High health provides immunity to debuff statuses"
    visual_effect: "conditional_immunity_indicator"
    audio_effect: "conditional_immunity_sound"
    
  # Immunity Rules
  rules:
    - rule_id: "conditional_immunity_calculation"
      rule_name: "Conditional Immunity Calculation"
      rule_name_vi: "Tính Toán Miễn Nhiễm Có Điều Kiện"
      rule_type: "immunity_calculation"
      rule_description: "Calculate conditional immunity based on specific conditions"
      rule_formula: "conditional_immunity = immunity_condition_met && immunity_type == target_type"
      
    - rule_id: "conditional_immunity_application"
      rule_name: "Conditional Immunity Application"
      rule_name_vi: "Áp Dụng Miễn Nhiễm Có Điều Kiện"
      rule_type: "immunity_application"
      rule_description: "Apply conditional immunity to status effect application"
      rule_formula: "status_blocked = conditional_immunity && target_status in immune_statuses"
      
    - rule_id: "conditional_immunity_condition_processing"
      rule_name: "Conditional Immunity Condition Processing"
      rule_name_vi: "Xử Lý Điều Kiện Miễn Nhiễm Có Điều Kiện"
      rule_type: "condition_processing"
      rule_description: "Process conditional immunity conditions and trigger effects"
      rule_formula: "condition_trigger = immunity_condition && condition_active"
      
  # Immunity Modifiers
  modifiers:
    - modifier_id: "conditional_immunity_condition_multiplier"
      modifier_name: "Conditional Immunity Condition Multiplier"
      modifier_name_vi: "Hệ Số Nhân Điều Kiện Miễn Nhiễm Có Điều Kiện"
      modifier_type: "multiplier"
      base_value: 1.0
      scaling_factor: 0.01
      scaling_stat: "constitution"
      
    - modifier_id: "conditional_immunity_condition_modifier"
      modifier_name: "Conditional Immunity Condition Modifier"
      modifier_name_vi: "Sửa Đổi Điều Kiện Miễn Nhiễm Có Điều Kiện"
      modifier_type: "condition"
      base_value: 0.0
      scaling_factor: 0.01
      scaling_stat: "wisdom"
      
  # Immunity Interactions
  interactions:
    - interaction_id: "conditional_immunity_with_healing"
      interaction_name: "Conditional Immunity with Healing"
      interaction_name_vi: "Miễn Nhiễm Có Điều Kiện với Hồi Máu"
      interaction_type: "conflict"
      target_immunity: "healing_immunity"
      interaction_behavior: "reduce_effectiveness"
      interaction_modifier: 0.5
      
    - interaction_id: "conditional_immunity_with_resistance"
      interaction_name: "Conditional Immunity with Resistance"
      interaction_name_vi: "Miễn Nhiễm Có Điều Kiện với Kháng Cự"
      interaction_type: "resistance"
      target_immunity: "resistance_immunity"
      interaction_behavior: "reduce_duration"
      interaction_modifier: 0.7
      
  # Immunity Immunity
  immunity:
    - immunity_id: "conditional_immunity_immunity"
      immunity_name: "Conditional Immunity Immunity"
      immunity_name_vi: "Miễn Nhiễm Miễn Nhiễm Có Điều Kiện"
      immunity_type: "complete"
      immunity_condition: "element_mastery_above_100"
      immunity_duration: "permanent"
      
  # Immunity Visual Effects
  visual_effects:
    - effect_id: "conditional_immunity_indicator"
      effect_name: "Conditional Immunity Indicator"
      effect_name_vi: "Chỉ Báo Miễn Nhiễm Có Điều Kiện"
      effect_type: "indicator_effect"
      indicator_type: "immunity"
      indicator_color: "#4ecdc4"
      indicator_intensity: 0.7
      
  # Immunity Audio Effects
  audio_effects:
    - effect_id: "conditional_immunity_sound"
      effect_name: "Conditional Immunity Sound"
      effect_name_vi: "Âm Thanh Miễn Nhiễm Có Điều Kiện"
      effect_type: "ambient_sound"
      sound_type: "immunity"
      volume: 0.6
      loop: true
