# Curse Status Configuration
# Debuff Status - Dark Element
status_definition:
  # Basic Info
  status_id: "curse"
  status_guid: "550e8400-e29b-41d4-a716-446655440004"
  world_id: "chaos_world_001"
  status_name: "Curse"
  status_name_vi: "Lời Nguyền"
  
  # Categories (multiple)
  categories: ["debuff", "dark_element", "resource_drain"]
  
  # Element Binding
  elements:
    primary_element: "dark"
    secondary_elements: ["curse", "drain"]
    element_affinity: 0.85
    
  # Basic Properties
  effect_type: "debuff"
  priority: 120
  stackable: true
  max_stacks: 5
  stack_behavior: "stack_additive"
  
  # Immunity System
  immunity_system:
    mechanical_immunity:
      - condition: "dead"
        immunity_type: "all_debuff_status"
        reason: "Dead actors cannot receive debuff status"
        
    logical_immunity:
      - condition: "dark_element_mastery_above_100"
        immunity_type: "curse"
        reason: "High dark mastery provides natural curse resistance"
        
    temporary_immunity:
      - condition: "just_removed_curse"
        immunity_type: "curse"
        duration: 10.0
        reason: "Temporary immunity after curse removal"
  
  # Status Effects
  effects:
    - effect_id: "resource_drain"
      effect_type: "resource_modifier"
      magnitude:
        base_value: 0.15
        scaling_factor: 0.02
        scaling_stat: "intelligence"
      duration:
        base_duration: 20.0
        scaling_factor: 0.1
        scaling_stat: "constitution"
      conditions:
        - condition_type: "resource_category_condition"
          resource_categories: ["life", "stamina", "lifespan"]
          modifier_type: "consumption_increase"
        - condition_type: "tick_condition"
          tick_interval: 1.0
          tick_count: 20
      triggers:
        - trigger_type: "on_resource_consumption"
          trigger_data:
            resource_categories: ["life", "stamina", "lifespan"]
      modifiers:
        - modifier_type: "resource_consumption_multiplier"
          value: 1.15
          source: "curse_effect"
        - modifier_type: "stacking_multiplier"
          value: 0.15
          source: "curse_stacking"
      interactions:
        - interaction_type: "stack_with"
          target_status: "curse"
          max_stacks: 5
      immunity_list:
        - "curse_immunity"
        - "debuff_immunity"
      movement_restrictions: []
      visual_effects:
        - effect_type: "aura_effect"
          effect_name: "dark_aura"
          duration: 20.0
          intensity: 1.0
      audio_effects:
        - effect_type: "ambient_sound"
          sound_name: "curse_whisper"
          volume: 0.6
          loop: true

  # Dynamic Scaling System
  scaling_system:
    level_scaling:
      base_level: 1
      max_level: 100
      scaling_formula: "exponential"
      scaling_factor: 1.1
      
    stat_scaling:
      primary_stat: "intelligence"
      secondary_stat: "constitution"
      tertiary_stat: "wisdom"
      scaling_weights: [0.5, 0.3, 0.2]

  # Conditional Effects
  conditional_effects:
    - condition: "target_dark_mastery_above_100"
      effect_modifier: 0.5
      effect_type: "magnitude_multiplier"
      
    - condition: "target_life_mastery_above_100"
      effect_modifier: 0.7
      effect_type: "magnitude_multiplier"

  # Environment Interactions
  environment_interactions:
    - environment: "dark_realm"
      effect_modifier: 1.5
      effect_type: "magnitude_multiplier"
      
    - environment: "light_realm"
      effect_modifier: 0.5
      effect_type: "magnitude_multiplier"

  # Time-based Modifiers
  time_modifiers:
    - time_period: "day"
      effect_modifier: 0.8
      effect_type: "magnitude_multiplier"
      
    - time_period: "night"
      effect_modifier: 1.2
      effect_type: "magnitude_multiplier"

  # Relationship-based Effects
  relationship_effects:
    - relationship: "ally"
      effect_modifier: 0.0
      effect_type: "magnitude_multiplier"
      
    - relationship: "enemy"
      effect_modifier: 1.0
      effect_type: "magnitude_multiplier"
